# Generated by Django 5.0.2 on 2024-02-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_adress_user_address_rename_rol_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('erkak', 'ERKAK'), ('ayol', 'AYOL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'ADMIN'), ('teacher', 'TEACHER'), ('student', 'STUDENT')], max_length=255, null=True),
        ),
    ]
