# Generated by Django 5.0.2 on 2024-02-17 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student_id',
        ),
        migrations.AddField(
            model_name='group',
            name='student_id',
            field=models.ManyToManyField(related_name='group_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
