# Generated by Django 5.0.2 on 2024-02-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_attendance_is_active_group_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='week_id',
            field=models.ManyToManyField(blank=True, related_name='group_week', to='structure.week'),
        ),
    ]
