# Generated by Django 5.0.2 on 2024-02-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
